ci: Allow only deploy
ehabshaaban/awesome-eyes pull request #11
Opened 2022-06-17 17:59 UTC by ehabshaaban

- [x] Add remote backend

2022-06-19 01:04 UTC, omarahm3 requested changes

2022-06-19 01:04 UTC, omarahm3 commented on versions.tf
> +      version = "2.11.0"
Are we sure that this version is stable enough to upgrade to ? if not please do a round of tests just to be 100% sure

2022-06-19 01:04 UTC, omarahm3 commented on versions.tf
> +      version = "2.5.1"
Same here

2022-06-19 01:04 UTC, omarahm3 commented on .github/actions/setup/action.yml
> +      run: terraform init
What was the actual change here?

2022-06-19 01:04 UTC, omarahm3 commented on .github/workflows/terraform-deploy.yml
> +      # - name: Terraform test
Don't ever add code comments to production ready code, please remove

2022-06-19 01:04 UTC, omarahm3 commented on .github/workflows/terraform-deploy.yml
> +      #   run: TF_VAR_grafana_admin_password=${{ env.PASSWD }} terraform destroy --auto-approve
Same here

2022-06-19 01:04 UTC, omarahm3 commented on .github/workflows/terraform-deploy.yml
> +        run: TF_VAR_grafana_admin_password=${{ env.PASSWD }} terraform apply --auto-approve
why `PASSWD` you're not shortening anything! its just confusing and not even `PASS` as any convention, please rename it to `PASSWORD` instead

2022-06-19 01:06 UTC, omarahm3 commented
> * [x]  Add remote backend

WTF is this description? 

Please add proper PR description, so that reviewers can understand actually the reason behind fix/feat/chore/...whatever you're doing.

2022-06-21 11:29 UTC, mohammedx3 approved these changes

2022-08-13 10:58 UTC, merged