Add test for helm charts
ehabshaaban/awesome-eyes pull request #9
Opened 2022-05-25 12:58 UTC by ehabshaaban

- [x] generate kubernetes clientset
- [x] write clientConfig in `~/.kube/config`
- [x] ValidatePrometheusDeployment
- [x] ValidateGrafanaDeployment

2022-05-26 22:06 UTC, omarahm3 commented on test/infra_test.go
> +			TLSClientConfig: rest.TLSClientConfig{
im on mobile so i cant check, but looks like indentation is not right. please make sure that you run `go fmt` on whole file

2022-05-27 11:01 UTC, ehabshaaban commented on .github/workflows/terraform-deploy.yml
> +        run: cd test && go test -v -timeout 3000s infra_test.go
You're right. But'll choose not to do it for the moment.

2022-05-27 11:30 UTC, ehabshaaban commented on test/infra_test.go
`RecommendedHomeDir`: is `.kube` directory
`RecommendedFileName`: is name of config file
`RecommendedHomeFile`: is machine instance home directory + `.kube` directory + name of config file
Where is the naming conflict is coming from?

2022-05-27 16:26 UTC, omarahm3 requested changes

2022-05-27 16:26 UTC, omarahm3 commented on test/infra_test.go
> +		var filter string = "server"
use short assignment instead

2022-05-27 16:26 UTC, omarahm3 commented on test/infra_test.go
> +		var filter string = "server"
Actually you can use "server" directly no need to use in a variable at all, or move to const

2022-05-28 03:28 UTC, omarahm3 approved these changes

2022-05-28 17:21 UTC, merged